### ISSUE TITLE
FYI, IDEA EAP and DynamicTests

### ISSUE THREAD

**Issue by k1w1m8** [sormuras/sormuras.github.io#2]
Sorry to ping you like this, not sure how else to contact you. 

I noticed you are involved in JUnit 5 dynamic tests and use IDEA. I saw this which looks fantastic!

https://sormuras.github.io/blog/2018-09-05-junit-5.3-dynamic-test-source.html

I'm a big user of dynamic testing, and I have been testing DynamicTests with latest IDEA. Not sure if you have used it, but they fixed the biggest issue (the name)

https://youtrack.jetbrains.com/issue/IDEA-193770

But they introduced some serious regressions as well, unfortunately, eg

https://youtrack.jetbrains.com/issue/IDEA-200641
https://youtrack.jetbrains.com/issue/IDEA-200501

Hopefully IDEA will fix these issues before the upcoming formal 2018.3 release. 

So, now is a good time to test the EAP if you are not already doing so....

**Comment by k1w1m8** [comment]
actually, while I am here, my test data has many files per test on disk.
so, should the URI parameter accept a directory? It doesn't seem to work in IDEA EAP.

**Comment by k1w1m8** [comment]
Actually, both of those are JUnit3 API regressions. You might not be that interested in those.

But you might be interested in theses one which are for JUnit5

https://youtrack.jetbrains.com/issue/IDEA-193776
https://youtrack.jetbrains.com/issue/IDEA-193824

**Comment by sormuras** [comment]
Hi @k1w1m8 -- and pardon my silence. Was offline for some days.

I'll upvote those issues you mentioned and try to support @akozlova be fixing them. ;-)

**Comment by k1w1m8** [comment]
Thanks. No need to apologise, I was not expecting a lot ;-)

Its just good to socialise the work being done around to make DynamicTests more usable in the real world, since it seems its a bit of a niche area. I'm especially looking forward to maven improvements in this area...

**Comment by sormuras** [comment]
> ...maven improvements...

Come over and make them happen! ;-)
https://github.com/apache/maven-surefire

On topic: IDEA 2018.3 Beta is in a better and Anna is on it, methinks.

**Comment by k1w1m8** [comment]
I know, I would like to and I know they need the help, but I am overloaded at the moment.

I took the Beta, its two steps forward, one step back. I am still finding issues. For example, 
* using testSourceURI breaks Rerun Failed Tests: https://youtrack.jetbrains.com/issue/IDEA-201375
* auto download of JUnit jars always triggering: https://youtrack.jetbrains.com/issue/IDEA-201374

I am super keen to move my users from TestSuite/TestCase to Dynamic Tests, I just need an IDE which can work with it properly... the wait is longer than I had hoped ...

**Comment by sormuras** [comment]
> https://youtrack.jetbrains.com/issue/IDEA-193776
> https://youtrack.jetbrains.com/issue/IDEA-193824

Both issues are marked as fixed.

**Comment by k1w1m8** [comment]
I'm about to retest in 2019.1 EAP. Hopefully it will all be good. But somehow, there always seems to be one more thing... ;-)

I noticed some changes you did in SUREFIRE-1546. Appreciate the effort there!
